DROP DATABASE IF EXISTS EMPRESTIMOS;
CREATE DATABASE EMPRESTIMOS;
USE EMPRESTIMOS;

CREATE TABLE EMPRESTIMOS.USUARIO(
	ID_USUARIO INT NOT NULL,
    NOME_USUARIO VARCHAR (45) NOT NULL,
    CPF_USUARIO INT (11) NOT NULL,
	EMAIL_USUARIO VARCHAR (45) NOT NULL,
    LOGIN_USUARIO VARCHAR (45) NOT NULL,
    SENHA_USUARIO VARCHAR (45) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE EMPRESTIMOS.ITEM(
	ID_ITEM INT NOT NULL,
    ID_DONO INT NOT NULL,
    NOME_ITEM VARCHAR (45) NOT NULL,
    DESCRICAO_ITEM VARCHAR (45) NOT NULL,
    CATEGORIA_ITEM VARCHAR (45) NOT NULL,
    PRIMARY KEY (ID_ITEM),
	FOREIGN KEY (ID_DONO) REFERENCES EMPRESTIMOS.USUARIO(ID_USUARIO)
);

CREATE TABLE EMPRESTIMOS.USU_ITEM(
	ID_ITEM INT,
    ID_USUARIO INT,
   
    PRIMARY KEY (ID_ITEM, ID_USUARIO),
    FOREIGN KEY (ID_ITEM) REFERENCES EMPRESTIMOS.ITEM(ID_ITEM),
	FOREIGN KEY (ID_USUARIO) REFERENCES EMPRESTIMOS.USUARIO(ID_USUARIO)
);


INSERT INTO EMPRESTIMOS.USUARIO VALUES
	(1, "Joao",00000000000,"fuluno1@gmail.com", "login1",1234 ),
    (2, "pedro",00000000000,"fuluno2@gmail.com", "login2",12345 ),
    (3, "maria",00000000000,"fuluna@gmail.com", "login3",123456 );
    
INSERT INTO EMPRESTIMOS.ITEM VALUES
	(1,1, "caneta","caneta preta", "objeto"),
    (2,2, "celular","celular motorola", "eletronicos"),
    (3,3, "camiseta","camiseta branca", "roupas");

INSERT INTO EMPRESTIMOS.USU_ITEM VALUES
	(1,2),
    (2,3), 
    (3,1); 